name: Sign deb or rpm asset package

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to get / upload the package'
        required: true
      package:
        description: 'Package name to sign'
        required: true

jobs:
  sign_asset:
    name: 'Sign asset'
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create packages folder
        run: mkdir packages

      - name: Fetch Github Release Asset
        uses: dsaltares/fetch-gh-release-asset@1.1.0
        with:
          file: ${{ github.event.inputs.package }}
          version: tags/${{ github.event.inputs.tag }}
          target: packages/${{ github.event.inputs.package }}

      - name: Sign package
        run: |
          sudo apt-get install -y debsigs
          bash ./scripts/sign.sh

      - name: Upload signed asset
        run: bash ./scripts/upload_assets_gh.sh
